theme: jekyll-theme-midnight
title: SpaceVim
description: A community-driven vim distribution
show_downloads: false
google_analytics: UA-89745542-1
gitment_client_id: 8f0cd1f544d1e4219798
gitment_client_secret: a673bd197859abb8f0157b91eedf85bcbc7e4f61
project_repo_url: https://github.com/SpaceVim/SpaceVim
url: https://spacevim.org
logo: https://spacevim.org/SpaceVim.png
permalink: /:title/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

github: [metadata]

webmaster_verifications:
  google: 2QrXyd7Wz5_ahXqefiYC_4-HvynQrefWDWORb7EjLCU

sass:
 sass_dir: _sass
 style: compressed

author:
      name: Shidong Wang
      twitter: SpaceVim
twitter:
    username: "@SpaceVim"

social:
  name: SpaceVim
  links:
      - https://twitter.com/SpaceVim
      - https://github.com/SpaceVim/SpaceVim
      - https://www.reddit.com/r/SpaceVim/

defaults:
  - scope:
      path: ""
    values:
      image: https://user-images.githubusercontent.com/13142418/46148881-a17f6400-c29b-11e8-9981-4915b4e3e733.png
