theme: jekyll-theme-midnight
title: SpaceVim
description: A community-driven Vim distribution
show_downloads: false
google_analytics: UA-89745542-1
project_repo_url: https://github.com/SpaceVim/SpaceVim
url: https://spacevim.org

permalink: /:title/

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
