name: mirror

on: [push]

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        mirror: ["gitee", "coding"]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Push to ${{ matrix.mirror }}
      env:
        BOTSECRET: ${{ secrets.BOTSECRET }}
        BOTSECRET_GITHUB: ${{ secrets.BOTSECRET_GITHUB }}
        CODINGBOTSECRET: ${{ secrets.CODINGBOTSECRET }}
      run: .ci/update_mirror.sh ${{ matrix.mirror }}

